version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "byRoadrunner"
    reviewers:
      - "byRoadrunner"
